name: harrier_central
description: A mobile app to manage your Hash House Harriers life.
version: 0.8.11+160

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.5.4-hotfix.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # last checked 20 Feb 2019
  # one incompatibility with permission_handler (see below) 
  audioplayers: ^0.10.0
  auto_size_text: ^1.1.2
  cached_network_image: ^0.8.0
  chewie: ^0.9.7
  crypto: ^2.0.6
  cupertino_icons: ^0.1.2
  fancy_bottom_navigation: ^0.3.2
  firebase_messaging: ^5.0.3
  flutter_facebook_login: ^2.0.1 # upgraded from 2.0.0 8 Jun 19 
  flutter_full_pdf_viewer: ^1.0.4
  flutter_image_compress: ^0.4.0 
  flutter_linkify: ^2.1.0
  flutter_map: ^0.4.0   # latest version is 0.5.0, but it depends on cached_network_image 0.5.1 - 19 March 2019
  flutter_speed_dial: ^1.2.1   # updated from 1.1.2 on 8 Jun 19
  flutter_spinkit: ^3.1.0 
  flutter_staggered_grid_view: ^0.2.7 
  flutter_vector_icons: ^0.1.0
  geolocator: ^4.0.3
  http: ^0.12.0+2
  image_cropper: ^1.0.2 # updated from 1.0.0 on 8 Jun 19
  image_picker: ^0.6.0+9 # from 0.5.4 May 20 # updated from 0.6.0+4 on 8 Jun 19
  intro_slider: ^1.2.3
  # location_permissions: ^2.0.1
  package_info: ^0.4.0+4 # updated from 0.4.0+3 on 8 Jun 19
  permission_handler: ^3.1.0 # updated from 2.2.0 on 8 Jun 19
  qr_flutter: ^2.1.0+55 # updated from 2.0.0 on 8 Jun 19
  shared_preferences: ^0.5.3+1 # updated from 0.5.2 on 8 Jun 19
  sqflite: ^1.1.5
  tinycolor: ^1.0.2
  url_launcher: ^5.0.3 # updated from 5.0.2 on 8 Jun 19
  utf: ^0.9.0
  video_player: ^0.10.1 # from ^0.10.0+8 May 20
  zoomable_image: ^1.3.1
  
  fast_qr_reader_view: 
    git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git

  # barcode_scan:
  #   git:
  #     url: git://github.com/apptreesoftware/flutter_barcode_reader.git
  # #     ref: 2.0.0-dev.1
  # # barcode_scan: git: https://github.com/apptreesoftware/flutter_barcode_reader.git 


  device_info: ^0.4.0+2
  # fast_qr_reader_view: ^0.1.5 - incompatible with AndroidX

  # Dependencies added to get geolocator working correctly. Check to see if the geolocator dependencies have been resolved in April 2019
  google_api_availability: 2.0.0 # Geolocator Dependency.
  meta: 1.1.6 # Geolocator Dependency.



  # # flip_panel: ^1.0.0
  # # qr_mobile_vision: ^0.1.0
  # # polygon_clipper 1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.5 # updated from 0.17.4 on 8 Jun 19


  flutter_launcher_icons: ^0.7.2 # updated from 0.7.0 on 8 Jun 19

flutter_icons:
  android: true 
  ios: 'HarrierCentralIcon'
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#FFE02000'
  adaptive_icon_foreground: 'assets/icon/hc_app_icon_adaptive_foot.png'

  # hc_app_icon_adaptive_foot

#flutter pub pub run flutter_launcher_icons:main


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  
  uses-material-design: true

  assets:
    - assets/
    - assets/documents/privacy_policy.pdf
    - assets/sounds/camera.mp3
    - database/cities.json
    - database/regions.json
    - database/countries.json
    - images/avatars/
    - images/backgrounds/
    - images/generic_logos/
    - images/icons/
    - images/init/
    - images/init/intro/
    - images/other/

  fonts:
    - family: AvenirNextHeavy
      fonts:
        - asset: fonts/AvenirNext-Heavy.ttf
        - asset: fonts/AvenirNext-HeavyItalic.ttf
          style: italic

    - family: AvenirNextBold
      fonts:
        - asset: fonts/AvenirNext-Bold.ttf
        - asset: fonts/AvenirNext-BoldItalic.ttf
          style: italic

    - family: AvenirNext
      fonts:
        - asset: fonts/AvenirNext-Regular.ttf
        - asset: fonts/AvenirNext-Italic.ttf
          style: italic

    - family: AvenirNextRegular
      fonts:
        - asset: fonts/AvenirNext-Regular.ttf
        - asset: fonts/AvenirNext-Italic.ttf
          style: italic


    - family: AvenirNextUltraLight
      fonts:
        - asset: fonts/AvenirNext-UltraLight.ttf
        - asset: fonts/AvenirNext-UltraLightItalic.ttf
          style: italic


    - family: AvenirNextMedium
      fonts:
        - asset: fonts/AvenirNext-Medium.ttf
        - asset: fonts/AvenirNext-MediumItalic.ttf
          style: italic

    - family: AvenirNextCondensed
      fonts:
        - asset: fonts/AvenirNextCondensed-Heavy.ttf
        - asset: fonts/AvenirNextCondensed-HeavyItalic.ttf
        - asset: fonts/AvenirNextCondensed-Italic.ttf
        - asset: fonts/AvenirNextCondensed-Regular.ttf
        - asset: fonts/AvenirNextCondensed-UltraLight.ttf
        - asset: fonts/AvenirNextCondensed-UltraLightItalic.ttf

    - family: AvenirNextCondensedMedium
      fonts:
        - asset: fonts/AvenirNextCondensed-Medium.ttf
        - asset: fonts/AvenirNextCondensed-MediumItalic.ttf
          style: italic
          
    - family: AvenirNextCondensedDemiBold
      fonts:
        - asset: fonts/AvenirNextCondensedDemiBold.ttf
        - asset: fonts/AvenirNextCondensedDemiBoldItalic.ttf
          style: italic

    - family: AvenirNextDemiBold
      fonts:
        - asset: fonts/AvenirNextDemiBold.ttf
        - asset: fonts/AvenirNextDemiBoldItalic.ttf
          style: italic
    - family: AvenirNextCondensedBold
      fonts:
        - asset: fonts/AvenirNextCondensedBold.ttf
        - asset: fonts/AvenirNextCondensedBoldItalic.ttf
          style: italic
 
