name: harrier_central
description: A mobile app to manage your Hash House Harriers life.
version: 1.0.19+519
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"
  flutter: ^2.5.2

dependencies:

  # last checked 20 Feb 2019
  # one incompatibility with permission_handler (see below)    
  audioplayers: ^0.20.1 # upgraded Sep 21 21 from 0.20.0 # upgraded Mar 23 21 from 0.17.1 # upgraded Jun 21 20 from 0.13.7 # upgraded Feb 02 from ^0.13.5 # upgraded Dec 19 from ^0.13.2 # updated on 11 Sep from 0.13.1 # updated from ^0.10.0 on 29 Jul
  auto_size_text: ^2.1.0 # updated on 11 Sep from 2.0.2+1 #updated from ^1.1.2 on 29 Jul
  cached_network_image: ^3.1.0  # upgraded Sep 21 21 from 2.5.1 # upgraded Mar 23 21 from 2.5.0 # updated Jan 20 from 2.2.0+1  # upgraded Jun 21 20 from 2.0.0 # upgraded Feb 02 from ^2.0.0-rc # upgraded Dec 19 from ^1.1.3 # upgraded Nov 10 from ^1.1.1 # upgraded from 0.8.0 on 28 Jul
  chewie: ^1.2.2  # upgraded Sep 21 21 from 1.0.0  # upgraded Mar 30 21 from 0.12.2 # downgraded Mar 29 21 from 1.0.0 # upgraded Mar 23 21 from 0.12.1+1 # updated Jan 20 from 0.9.10 # upgraded 7 Apr 20 from ^0.9.8+1 # upgraded Nov 10 from ^0.9.8 # updated on 11 Sep from 0.9.7
  crypto: ^3.0.1  # upgraded Sep 21 21 from 2.1.5  # upgraded Jun 21 20 from 2.1.3 # updated on 11 Sep from 2.0.6
  cupertino_icons: ^1.0.3  # upgraded Sep 21 21 from 1.0.0 # downgraded Mar 29 21 from 1.0.2 # upgraded Mar 23 21 from 1.0.0 # updated Jan 20 from 0.1.3 # upgraded Dec 19 from ^0.1.2
  date_time_picker: 2.0.0  # upgraded Sep 21 21 from 1.1.1
  device_info: ^2.0.2  # upgraded Sep 21 21 from 2.0.0 # upgraded Mar 30 21 from 1.0.0 # downgraded Mar 29 21 from 2.0.0 # upgraded Mar 23 21 from 1.0.0 # updated Jan 20 from 0.4.2+4  # upgraded Jun 21 20 from 0.4.2+1 # upgraded 7 Apr 20 from 0.4.1+5 # upgraded Feb 25 2020 from 0.4.1+4 # upgraded Dec 19 from ^0.4.1+1 # upgraded Nov 10 from ^0.4.0+2
  # email_validator: ^2.0.1 # upgraded Mar 30 21 from 1.0.6 # downgraded Mar 29 21 from 2.0.1 # upgraded Mar 23 21 from 1.0.6 # updated Jan 20 from 1.0.4
  fancy_bottom_navigation: ^0.3.3  # upgraded Sep 21 21 from 0.3.2 # downgraded Mar 29 21 from 0.3.3 # upgraded Mar 23 21 from 0.3.2
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7  # upgraded Sep 21 21 from 7.0.3 # updated Jan 20 from 6.0.16  # upgraded Jun 21 20 from 5.1.8 # upgraded Nov 10 from ^5.1.5 # updated on 11 Sep from 5.1.2 # upgraded from 5.0.4 on 28 Jul #upgraded from 5.0.3 on 5 Jul 19
  # flutter_facebook_login: ^3.0.0 # upgraded from 2.0.1 17 Jan # upgraded from 2.0.0 8 Jun 19 
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.2 # upgraded Sep 27 21 from 3.5.1 # upgraded Sep 21 21 from 2.0.1+1 # upgraded Mar 23 21 from 2.0.1
  flutter_image: ^4.1.0  # upgraded Sep 21 21 from 3.0.0 # upgraded Dec 19 from ^2.0.1 # upgraded Nov 10 from ^2.0.0c
  flutter_image_compress: ^1.1.0 # upgraded Sep 21 21 from 1.0.0 # upgraded Mar 30 21 from 0.7.0 # updated Jan 20 from 0.6.8  # upgraded Jun 21 20 from 0.6.5+1 # upgraded Feb 02 from ^0.6.3 # upgraded from 0.4.0 on 28 Jul
  flutter_linkify: ^5.0.2  # upgraded Sep 21 21 from 5.0.0 # upgraded Mar 30 21 from 4.1.0 # downgraded Mar 29 21 from 5.0.0 # upgraded Mar 23 21 from 4.0.2 # updated Jan 20 from 3.1.3  # upgraded Jun 21 20 from 2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0  # upgraded Sep 21 21 from 0.12.0 # upgraded Mar 30 21 from 0.11.0 # downgraded Mar 29 21 from 0.12.0 # upgraded Mar 23 21 from 0.10.1+1 # updated Jan 20 from 0.9.0  # upgraded Jun 21 20 from 0.8.2 # upgraded Mar 21 from ^0.8.0 # upgraded Dec 19 from ^0.7.3 # upgraded Nov 10 from ^0.7.2 # updated on 11 Sep from 0.7.0+1 # upodated from 0.4.0 on 29 Jul # latest version is 0.5.0, but it depends on cached_network_image 0.5.1 - 19 March 2019
  flutter_map_marker_cluster: ^0.4.0 # upgraded Sep 21 21 from 0.3.1 # downgraded Mar 29 21 from 0.3.4 # upgraded Mar 23 21 from 0.3.1 # updated Jan 20 from 0.2.8  # upgraded Jun 21 20 from 0.2.7
  flutter_phoenix: ^1.0.0  # upgraded Sep 21 21 from 0.1.0
  # problem with SpeedDial 4.4.0 - will have to wait until I can upgrade SDK to >=2.5.0
  flutter_slidable: ^0.6.0 
  flutter_speed_dial: 4.3.0 # upgraded Sep 21 21 from 3.0.5 # upgraded Mar 30 21 from 2.1.1 # downgraded Mar 29 21 from 3.0.5 # upgraded Mar 23 21 from 1.2.5 # upgraded Dec 19 from ^1.2.1   # updated from 1.1.2 on 8 Jun 19
  flutter_staggered_grid_view: ^0.4.0 # upgraded Sep 21 21 from 0.3.4 # upgraded Mar 23 21 from 0.3.3 # updated Jan 20 from 0.3.0 # upgraded from ^0.2.7 on 29 Jul
  flutter_swiper: ^1.1.6
  flutter_vector_icons: ^1.0.0 # upgraded Mar 30 21 from 0.3.0 # downgraded Mar 29 21 from 1.0.0 # upgraded Mar 23 21 from 0.2.1 # updated on 11 Sep from 0.2.0 # upgraded from 0.1.0 on Jul 29
  geolocator: ^7.6.2 # upgraded Sep 21 21 from 5.3.2+2  # upgraded Jun 21 20 from 5.3.1 # upgraded 7 Apr 20 from 5.3.0 # upgraded Feb 25 2020 from 5.2.1 # upgraded Feb 02 from ^5.1.5 # upgraded Nov 10 from ^5.1.3 # updated on 11 Sep from 5.1.1+1 #upgraded from ^4.0.3 on Jul 29
  get_it: ^7.2.0 # upgraded Sep 21 21 from 6.0.0  # updated on 26 Mar '21 from 5.0.1 # updated on 22 Oct '20 from 4.0.4
  google_api_availability: ^3.0.1 # upgraded Sep 21 21 from 2.0.4 # upgraded 7 Apr 20 from 2.0.2 # upgraded Feb 02 from ^2.0.1 # upgraded from 2.0.0 on 29 Jul # Geolocator Dependency.
  http: ^0.13.3 # upgraded Sep 21 21 from 0.13.1 # updated Jan 20 from 0.12.1  # upgraded Jun 21 20 from 0.12.0+4 # upgraded Feb 02 from ^0.12.0+2
  image_cropper: ^1.4.1 # upgraded Sep 21 21 from 1.3.1 # downgraded Mar 29 21 from 1.4.0 # upgraded Mar 23 21 from 1.3.1 # updated Jan 20 from 1.2.3  # upgraded Jun 21 20 from 1.2.1 # upgraded Feb 02 from ^1.1.2 # upgraded Dec 19 from ^1.1.0 # upgraded Nov 10 from ^1.0.2 # updated from 1.0.0 on 8 Jun 19
  image_picker: ^0.8.4+1 # upgraded Sep 21 21 from 0.6.7+22 # upgraded Mar 23 21 from 0.6.7+21 # updated Jan 20 from 0.6.7+2  # upgraded Jun 21 20 from 0.6.4 # upgraded 7 Apr 20 from 0.6.3+4 # upgraded Feb 25 2020 from 0.6.3+1 # upgraded Feb 02 from ^0.6.2+3 # upgraded Dec 19 from ^0.6.1+11 # upgraded Nov 10 from ^0.6.1+4 # updated on 11 Sep from 0.6.0+17 #updated from +10 on 29 Jul # updated from 0.6.0+4 on 8 Jun 19, updated from 0.6.0+8 on July 5
  intro_slider: ^3.0.2 # upgraded Sep 21 21 from 2.3.4 # upgraded Mar 23 21 from 2.3.3 # updated Jan 20 from 2.3.1  # upgraded Jun 21 20 from 2.2.9 # upgraded Feb 25 2020 from 2.2.8 # updated on 11 Sep from 2.2.5 # upgraded from ^1.2.3 Jul 29
  ive_flutter_core:
    git:
      url: git://github.com/InnoVet-Europe/ive_flutter_core.git
      ref: 8a22a083318d840cead0d694be7fa2e83c4012ad # Version 1.1.0+2 
  ive_flutter_core_mobile: 
    git:
      url: git://github.com/InnoVet-Europe/ive_flutter_core_mobile.git
      ref: b8a431387cf3f99b8ea0a0dfc99bfcee0ae1ec83 # 1.1.0+2 / 26 Mar 2021 
  # location_permissions: ^2.0.1
  keyboard_actions: ^3.4.4 # upgraded Sep 21 21 from 3.3.1+1
  keyboard_avoider: ^0.1.2
  # location_permissions: ^4.0.0  # upgraded Sep 21 21 from 3.0.0+1  # upgraded Jun 21 20 from 2.0.5 # upgraded 7 Apr 20 from 2.0.4+1
  meta: ^1.7.0 # upgraded Sep 21 21 from 1.3.0-nullsafety.3 # updated Jan 20 from 1.1.6  # Geolocator Dependency.
  package_info: ^2.0.2 # upgraded Sep 21 21 from 2.0.0 # upgraded Mar 30 21 from 0.4.3+4 # downgraded Mar 29 21 from 2.0.0 # upgraded Mar 23 21 from 0.4.3+2 # updated Jan 20 from 0.4.1  # upgraded Jun 21 20 from 0.4.0+16 # upgraded 7 Apr 20 from 0.4.0+14 # upgraded Feb 25 2020 from 0.4.0+13 # upgraded Dec 19 from ^0.4.0+10 # upgraded Nov 10 from ^0.4.0+6 # updated from +4 on 29 Jul # updated from 0.4.0+3 on 8 Jun 19
  pdf_viewer_plugin: ^2.0.1
  permission_handler: ^8.1.6 # upgraded Sep 21 21 from 5.0.1+2 # upgraded Mar 23 21 from 5.0.1+1 # updated Jan 20 from 5.0.1  # upgraded Jun 21 20 from 3.3.0 # upgraded Nov 10 from ^3.2.2 # updated on 11 Sep from 3.2.1+1 #updated from ^3.1.0 on 29 Jul # updated from 2.2.0 on 8 Jun 19
  # photo_view: ^0.4.2
  qonversion_flutter: ^4.2.0 # upgraded Sep 21 21 from 2.5.2
  qr_code_scanner: ^0.5.2 # upgraded Sep 21 21 from 0.3.5 # upgraded Mar 30 21 from 0.3.5 # upgraded Mar 23 21 from 0.0.13
  # qr_flutter: ^2.1.0+55 # updated from 2.0.0 on 8 Jun 19
  shared_preferences: ^2.0.7 # upgraded Sep 21 21 from 0.5.12+4 # updated Jan 20 from 0.5.7+3 # upgraded Jun 21 20 from 0.5.6+3 # upgraded 7 Apr 20 from 0.5.6+2 # upgraded Feb 25 2020 from 0.5.6+1 # upgraded Feb 02 from ^0.5.6 # upgraded Dec 19 from ^0.5.4+3 # upgraded Nov 10 from ^0.5.3+4 #updated from ^0.5.3+1 on Jul 29 # updated from 0.5.2 on 8 Jun 19
  sign_in_with_apple: ^3.2.0 # upgraded Sep 21 21 from 2.5.4
  sumup: ^0.2.5
  table_calendar: ^3.0.2 # upgraded Sep 21 21 from 2.3.3
  tinycolor: ^1.0.3 # updated Jan 20 from 1.0.2
  url_launcher: ^6.0.10 # upgraded Sep 21 21 from 6.0.3 # upgraded Mar 30 21 from 5.7.10 # downgraded Mar 29 21 from 6.0.2  # upgraded Mar 23 21 from 5.7.10 # updated Jan 20 from 5.4.11 # upgraded Jun 21 20 from 5.4.2 # upgraded Feb 25 2020 from 5.4.1 # upgraded Dec 19 from ^5.2.5 # upgraded Nov 10 from 5.1.2 # updated on 11 Sep from 5.1.1 #updated from ^5.0.3 on 29 Jul # updated from 5.0.2 on 8 Jun 19
  utf: ^0.9.0+5
  # video_player: ^1.0.1 # downgraded Mar 29 21 from 2.0.2 # upgraded Mar 23 21 from 1.0.1 # updated Jan 20 from 0.10.11+1 # upgraded Jun 21 20 from 0.10.8+1 # upgraded Feb 25 2020 from 0.10.6 # upgraded Feb 02 from ^0.10.5 # upgraded Dec 19 from ^0.10.2+5 # upgraded Nov 10 from 0.10.2+1 # updated on 11 Sep from 0.10.1+5 #updated from +3 on 29 Jul # from ^0.10.0+8 May 20, from 0.10.1 on 5 July
  
  # fast_qr_reader_view: 
  #   git:
  #     url: git://github.com/facundomedica/fast_qr_reader_view.git



  # # flip_panel: ^1.0.0
  # # qr_mobile_vision: ^0.1.0
  # # polygon_clipper 1.0.2
  # # country_pickers 1.1.0
  # # dash_chat 1.0.10 - great chat implementation!
  # # flutter_slidable 0.5.4
  # # location 2.5.4  --  switch to this!
  # # table_calendar 2.2.3
  # # bottom_navy_bar

dependency_overrides:
  meta: ^1.3.0
  photo_view: ^0.12.0

  
  # http: ^0.12.2
  # intl: any
  # json_annotation: ^3.1.1
  # path_provider: ^1.6.22


dev_dependencies: 
  # flutter_test:
  #   sdk: flutter
  build_runner: ^2.1.2 # upgraded Sep 21 21 from 1.11.4 # upgraded Jun 21 20 from 1.8.1
  flutter_launcher_icons: ^0.9.2 # upgraded Sep 21 21 from 0.8.1 # upgraded Mar 23 21 from 0.7.5 # upgraded Jun 21 20 from 0.7.4 # upgraded Nov 10 from ^0.7.3 # updated on 11 Sep from 0.7.2+1 # updated from 0.7.0 on 5 Jul 19 from 0.7.2
  # intl_translation: ^0.17.10+1 # upgraded Feb 02 from ^0.17.7 # updated on 11 Sep from 0.17.5 # updated from 0.17.4 on 8 Jun 19
  json_annotation: ^4.1.0 # upgraded Sep 21 21 from 3.1.1
  json_serializable: ^5.0.2 # upgraded Sep 21 21 from 3.5.1 # upgraded Mar 23 21 from 3.3.0

flutter_icons:
  android: true 
  ios: 'HarrierCentralIcon'
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#FFE02000'
  adaptive_icon_foreground: 'assets/icon/hc_app_icon_adaptive_foot.png'

  # hc_app_icon_adaptive_foot

#flutter pub pub run flutter_launcher_icons:main


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  
  uses-material-design: true

  assets:
    - assets/
    - assets/documents/privacy_policy.pdf
    - assets/sounds/camera.mp3
    - images/avatars/
    - images/backgrounds/
    - images/generic_logos/
    - images/logos/
    - images/icons/
    - images/init/
    - images/init/intro/
    - images/map_pins/yellow/
    - images/map_pins/green/
    - images/map_pins/teal/
    - images/map_pins/baby_blue/
    - images/map_pins/blue/
    - images/map_pins/purple/
    - images/map_pins/pink/
    - images/map_pins/orange/
    - images/map_pins/red/
    - images/other/
    - images/tutorial/

  fonts:
    - family: AvenirNextHeavy
      fonts:
        - asset: fonts/AvenirNext-Heavy.ttf
        - asset: fonts/AvenirNext-HeavyItalic.ttf
          style: italic

    - family: AvenirNextBold
      fonts:
        - asset: fonts/AvenirNext-Bold.ttf
        - asset: fonts/AvenirNext-BoldItalic.ttf
          style: italic

    - family: AvenirNext
      fonts:
        - asset: fonts/AvenirNext-Regular.ttf
        - asset: fonts/AvenirNext-Italic.ttf
          style: italic

    - family: AvenirNextRegular
      fonts:
        - asset: fonts/AvenirNext-Regular.ttf
        - asset: fonts/AvenirNext-Italic.ttf
          style: italic


    - family: AvenirNextUltraLight
      fonts:
        - asset: fonts/AvenirNext-UltraLight.ttf
        - asset: fonts/AvenirNext-UltraLightItalic.ttf
          style: italic


    - family: AvenirNextMedium
      fonts:
        - asset: fonts/AvenirNext-Medium.ttf
        - asset: fonts/AvenirNext-MediumItalic.ttf
          style: italic

    - family: AvenirNextCondensed
      fonts:
        - asset: fonts/AvenirNextCondensed-Heavy.ttf
        - asset: fonts/AvenirNextCondensed-HeavyItalic.ttf
        - asset: fonts/AvenirNextCondensed-Italic.ttf
        - asset: fonts/AvenirNextCondensed-Regular.ttf
        - asset: fonts/AvenirNextCondensed-UltraLight.ttf
        - asset: fonts/AvenirNextCondensed-UltraLightItalic.ttf

    - family: AvenirNextCondensedMedium
      fonts:
        - asset: fonts/AvenirNextCondensed-Medium.ttf
        - asset: fonts/AvenirNextCondensed-MediumItalic.ttf
          style: italic
          
    - family: AvenirNextCondensedDemiBold
      fonts:
        - asset: fonts/AvenirNextCondensedDemiBold.ttf
        - asset: fonts/AvenirNextCondensedDemiBoldItalic.ttf
          style: italic

    - family: AvenirNextDemiBold
      fonts:
        - asset: fonts/AvenirNextDemiBold.ttf
        - asset: fonts/AvenirNextDemiBoldItalic.ttf
          style: italic
    - family: AvenirNextCondensedBold
      fonts:
        - asset: fonts/AvenirNextCondensedBold.ttf
        - asset: fonts/AvenirNextCondensedBoldItalic.ttf
          style: italic
 
