// package imports
// ignore_for_file: avoid_unused_constructor_parameters

import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

import 'package:hcportal/imports.dart';

part 'run_details_model.freezed.dart';
part 'run_details_model.g.dart';

@freezed
abstract class RunDetailsModel with _$RunDetailsModel {
  factory RunDetailsModel({
    required String publicKennelId,
    required DateTime eventStartDatetime,
    required int isVisible,
    required int isCountedRun,
    required int isPromotedEvent,
    required int eventGeographicScope,
    required int eventNumber,
    required String eventName,
    required String eventDescription,
    required int extrasRsvpRequired,
    required int tags1,
    required int tags2,
    required int tags3,
    required int useFbLocation,
    required int useFbLatLon,
    required int useFbRunDetails,
    required int useFbImage,
    required int integrationEnabled,
    required int kenDisseminateHashRunsDotOrg,
    required int kenDisseminateAllowWebLinks,
    required int kenDisseminationAudience,
    required String countryId,
    required String countryName,
    String? publicEventId,
    int? evtDisseminationAudience,
    int? evtDisseminateAllowWebLinks,
    int? evtDisseminateHashRunsDotOrg,
    int? evtDisseminateOnGlobalGoogleCalendar,
    int? kenDisseminateOnGlobalGoogleCalendar,
    double? cityLatitude,
    double? cityLongitude,
    int? doTrackHashCash,
    int? inboundIntegrationId,
    String? kennelName,
    String? kennelCountryCodes,
    double? kennelDefaultEventPriceForMembers,
    double? kennelDefaultEventPriceForNonMembers,
    int? digitsAfterDecimal,
    String? currencySymbol,
    String? extEventName,
    DateTime? eventEndDatetime,
    DateTime? extDataLastUpdated,
    DateTime? extEventStartDatetime,
    double? hcLatitude,
    double? hcLongitude,
    double? fbLatitude,
    double? fbLongitude,
    double? kenLatitude,
    double? kenLongitude,
    String? kennelLogo,
    String? kennelShortName,
    String? kennelUniqueShortName,
    double? eventPriceForMembers,
    double? eventPriceForNonMembers,
    String? eventFacebookId,
    int? absoluteEventNumber,
    int? canEditRunAttendence,
    int? maximumParticipantsAllowed,
    int? minimumParticipantsRequired,
    int? eventChatMessageCount,
    String? eventImage,
    String? extEventImage,
    String? extEventDescription,
    String? extLocationOneLineDesc,
    String? extLocationPostCode,
    String? extLocationCity,
    String? extLocationStreet,
    String? extLocationCountry,
    String? extLocationRegion,
    String? extLocationSubRegion,
    String? locationOneLineDesc,
    String? locationPostCode,
    String? locationCity,
    String? locationStreet,
    String? locationCountry,
    String? locationRegion,
    String? locationSubRegion,
    String? locationPhoneNumber,
    String? hares,
    String? eventPaymentScheme,
    String? eventPaymentUrl,
    DateTime? eventPaymentUrlExpires,
    num? eventPriceForExtras,
    String? extrasDescription,
  }) = _RunDetailsModel;

  factory RunDetailsModel.fromJson(Map<String, dynamic> json) =>
      _$RunDetailsModelFromJson(json);

  factory RunDetailsModel.empty() => _$RunDetailsModelFromJson(
        json.decode(r'''
        {
        "absoluteEventNumber":null,
        "canEditRunAttendence":null,
        "cityLatitude": 0.0,
        "cityLongitude":0.0,
        "countryId":"A1325DE2-5519-4311-9F49-5AF17C37B62A",
        "countryName":"United Kingdom",
        "currencySymbol":"$^",
        "digitsAfterDecimal":2,
        "doTrackHashCash":0,
        "eventDescription":"",
        "eventEndDatetime":null,
        "eventFacebookId":null,
        "eventGeographicScope":1,

        "kenDisseminateHashRunsDotOrg":1,
        "kenDisseminateAllowWebLinks":1,
        "kenDisseminationAudience":15,
        "evtDisseminationAudience":null,
        "evtDisseminateAllowWebLinks":null,
        "evtDisseminateHashRunsDotOrg":null,
        "evtDisseminateOnGlobalGoogleCalendar":null,
        "kenDisseminateOnGlobalGoogleCalendar":1,

        "eventImage":null,
        "eventName":"",
        "eventNumber":0,
        "eventPaymentScheme":null,
        "eventPaymentUrl":null,
        "eventPaymentUrlExpires":null,
        "eventPriceForExtras":null,
        "eventPriceForMembers":null,
        "eventPriceForNonMembers":null,
        "eventStartDatetime":"2020-01-01 12:00:00.000",
        "extEventDescription":null,
        "extEventImage":null,
        "extEventName":null,
        "extEventStartDatetime":null,
        "extLocationCity":null,
        "extLocationCountry":null,
        "extLocationOneLineDesc":null,
        "extLocationPostCode":null,
        "extLocationRegion":null,
        "extLocationStreet":null,
        "extLocationSubRegion":null,
        "extrasDescription":null,
        "extrasRsvpRequired": 1,
        "fbLatitude":null,
        "fbLongitude":null,
        "hares":null,
        "hcLatitude":null,
        "hcLongitude":null,
        "inboundIntegrationId":0,
        "integrationEnabled":0,
        "isCountedRun":1,
        "isPromotedEvent":0,
        "isVisible":1,
        "kenLatitude":0.0,
        "kenLongitude":0.0,
        "kennelCountryCodes":"",
        "kennelDefaultEventPriceForMembers":0.0,
        "kennelDefaultEventPriceForNonMembers":0.0,
        "kennelLogo":"",
        "kennelName":"",
        "kennelShortName":"",
        "kennelUniqueShortName":"",
        "locationCity":null,
        "locationCountry":null,
        "locationOneLineDesc":null,
        "locationPostCode":null,
        "locationRegion":null,
        "locationStreet":null,
        "locationSubRegion":null,
        "maximumParticipantsAllowed":null,
        "minimumParticipantsRequired":null,
        "publicEventId":"00000000-0000-0000-0000-000000000000",
        "publicKennelId":"",
        "tags1":0,
        "tags2":0,
        "tags3":0,
        "useFbImage":0,
        "useFbLatLon":0,
        "useFbLocation":0,
        "useFbRunDetails":0}
        ''') as Map<String, dynamic>,
      );

  factory RunDetailsModel.newRecord(
    double cityLat,
    double cityLon,
    String defaultCurrencySymbol,
    int defaultDigitsAfterDecimal,
    double defaultEventPriceForMembers,
    double defaultEventPriceForNonMembers,
    DateTime eventRunStartDateTime,
    double? kennelLat,
    double? kennelLon,
    String kennelCountryCodes,
    double kennelDefaultEventPriceForMembers,
    double kennelDefaultEventPriceForNonMembers,
    String kennelLogo,
    String kennelName,
    String kennelShortName,
    String kennelUniqueShortName,
    String publicKennelId,
    int defaultTags1,
    int defaultTags2,
    int defaultTags3,
    String phoneNumber,
    String countryId,
    String countryName,
  ) =>
      _$RunDetailsModelFromJson(
        json.decode('''
      {
        "absoluteEventNumber":null,
        "canEditRunAttendence":null,
        "cityLatitude":$cityLat,
        "cityLongitude":$cityLon,
        "currencySymbol":"$defaultCurrencySymbol",
        "digitsAfterDecimal":$defaultDigitsAfterDecimal,
        "doTrackHashCash":0,
        "eventDescription":"",
        "eventEndDatetime":null,
        "eventFacebookId":null,
        "eventGeographicScope":1,
        "kenDisseminateHashRunsDotOrg":1,
        "kenDisseminateAllowWebLinks":1,
        "kenDisseminationAudience":15,
        "evtDisseminationAudience":null,
        "evtDisseminateAllowWebLinks":null,
        "evtDisseminateHashRunsDotOrg":null,
        "evtDisseminateOnGlobalGoogleCalendar":null,
        "kenDisseminateOnGlobalGoogleCalendar":1,
        "eventImage":null,
        "eventName":"",
        "eventNumber":0,
        "eventPaymentScheme":null,
        "eventPaymentUrl":null,
        "eventPaymentUrlExpires":null,
        "eventPriceForExtras":null,
        "eventPriceForMembers":$defaultEventPriceForMembers,
        "eventPriceForNonMembers":$defaultEventPriceForNonMembers,
        "eventStartDatetime":"${eventRunStartDateTime.toIso8601String()}",
        "extEventDescription":null,
        "extEventImage":null,
        "extEventName":null,
        "extEventStartDatetime":null,
        "extLocationCity":null,
        "extLocationCountry":null,
        "extLocationOneLineDesc":null,
        "extLocationPostCode":null,
        "extLocationRegion":null,
        "extLocationStreet":null,
        "extLocationSubRegion":null,
        "extrasDescription":null,
        "extrasRsvpRequired": 1,
        "fbLatitude":null,
        "fbLongitude":null,
        "hares":null,
        "hcLatitude":null,
        "hcLongitude":null,
        "inboundIntegrationId":0,
        "integrationEnabled":0,
        "isCountedRun":1,
        "isPromotedEvent":0,
        "isVisible":1,
        "kenLatitude":$kennelLat,
        "kenLongitude":$kennelLon,
        "kennelCountryCodes":"$kennelCountryCodes",
        "kennelDefaultEventPriceForMembers":$kennelDefaultEventPriceForMembers,
        "kennelDefaultEventPriceForNonMembers":$kennelDefaultEventPriceForNonMembers,
        "kennelLogo":"$kennelLogo",
        "kennelName":"$kennelName",
        "kennelShortName":"$kennelShortName",
        "kennelUniqueShortName":"$kennelUniqueShortName",
        "locationCity":null,
        "locationCountry":null,
        "locationOneLineDesc":null,
        "locationPostCode":null,
        "locationRegion":null,
        "locationStreet":null,
        "locationSubRegion":null,
        "locationPhoneNumber":null,
        "maximumParticipantsAllowed":null,
        "minimumParticipantsRequired":null,
        "publicEventId":null,
        "publicKennelId":"$publicKennelId",
        "tags1":$defaultTags1,
        "tags2":$defaultTags2,
        "tags3":$defaultTags3,
        "useFbImage":0,
        "useFbLatLon":0,
        "useFbLocation":0,
        "useFbRunDetails":0,
        "countryId":"$countryId",
        "countryName":"$countryName"
        }
        ''') as Map<String, dynamic>,
      );

  factory RunDetailsModel.test() => _$RunDetailsModelFromJson(
        json.decode('''
{
        "absoluteEventNumber":null,
        "canEditRunAttendence":0,
        "cityLatitude":52.15,
        "cityLongitude":4.483333001,
        "countryId":"A1325DE2-5519-4311-9F49-5AF17C37B62A",
        "countryName":"United Kingdom",
        "currencySymbol":"€^",
        "digitsAfterDecimal":2,
        "doTrackHashCash":0,
        "eventDescription":"Test Description from Harrier Central",
        "eventEndDatetime":"2022-03-22T02:20:00.000Z",
        "eventFacebookId":"279605883983114",
        "eventGeographicScope":2,
        "kenDisseminateHashRunsDotOrg":1,
        "kenDisseminateAllowWebLinks":1,
        "kenDisseminationAudience":15,
        "evtDisseminationAudience":null,
        "evtDisseminateAllowWebLinks":null,
        "evtDisseminateHashRunsDotOrg":null,
        "evtDisseminateOnGlobalGoogleCalendar":null,
        "kenDisseminateOnGlobalGoogleCalendar":1,
        "eventImage":"https://harriercentral.blob.core.windows.net/profile-photos/0233C087-7E3B-48A2-956A-35359BEA2AAF_20220101152407_thumb.jpg",
        "eventName":"Test Event local HC info",
        "eventNumber":9,
        "eventPaymentScheme":null,
        "eventPaymentUrl":null,
        "eventPaymentUrlExpires":null,
        "eventPriceForExtras":10.0,
        "eventPriceForMembers":7.60,
        "eventPriceForNonMembers":7.90,
        "eventStartDatetime":"2022-02-22T02:20:00.000Z",
        "extEventDescription":"Test Description",
        "extEventImage":"https://harriercentral.blob.core.windows.net/event-images/eventImage_279605883983114_14950595e1c56fd7336b1667e05e8ebd.jpg",
        "extEventName":"Test Event",
        "extEventStartDatetime":"2022-02-05T09:00:00.000Z",
        "extLocationCity":"Berlin",
        "extLocationCountry":"Deutschland",
        "extLocationOneLineDesc":"Test Location",
        "extLocationPostCode":"10623",
        "extLocationRegion":"Berlin",
        "extLocationStreet":"164 Kantstraße",
        "extLocationSubRegion":"Berlin",
        "extrasDescription":"Dinner",
        "extrasRsvpRequired": 1,
        "fbLatitude":52.50503,
        "fbLongitude":13.33297,
        "hares":null,
        "hcLatitude":52.2,
        "hcLongitude":4.4,
        "inboundIntegrationId":0,
        "integrationEnabled":0,
        "isCountedRun":1,
        "isPromotedEvent":1,
        "isVisible":1,
        "kenLatitude":52.1238,
        "kenLongitude":4.4386,
        "kennelCountryCodes":"NL,BE,DE",
        "kennelDefaultEventPriceForMembers":5,
        "kennelDefaultEventPriceForNonMembers":5,
        "kennelLogo":"https://harriercentral.blob.core.windows.net/harrier/hc_test_kennel.png",
        "kennelName":"Harrier Central Test Kennel",
        "kennelShortName":"HCTEST",
        "locationCity":"Voorschoten",
        "locationCountry":"Netherlands",
        "locationOneLineDesc":"Test Location",
        "locationPostCode":"2252AB",
        "locationRegion":"Zuid-Holland",
        "locationStreet":"Veurseweg 42",
        "locationSubRegion":null,
        "locationPhoneNumber":"+31 6 13 02 5115",
        "maximumParticipantsAllowed":40,
        "minimumParticipantsRequired":20,
        "publicEventId":"365DE94F-CC6C-49CB-BD1C-0392BDE90BAB",
        "publicKennelId":"03B4004D-5CCB-4BCA-804C-88965C54C7AE",
        "tags1":45,
        "tags2":17,
        "tags3":0,
        "useFbImage":0,
        "useFbLatLon":0,
        "useFbLocation":0,
        "useFbRunDetails":0}
        ''') as Map<String, dynamic>,
      );
}
