// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_z9Xbh3U55aQ1HJYn1WqfXkY5_aetpFE',
    appId: '1:699693953835:web:43c78891078029d87a8b6e',
    messagingSenderId: '699693953835',
    projectId: 'harrier-central-mobile',
    authDomain: 'harrier-central-mobile.firebaseapp.com',
    databaseURL: 'https://harrier-central-mobile.firebaseio.com',
    storageBucket: 'harrier-central-mobile.firebasestorage.app',
    measurementId: 'G-2B04ZP86XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwo7nAC02nMVQn36ULyyKIgmnKaxP5XKs',
    appId: '1:699693953835:android:c1ecc92cad9ee9967a8b6e',
    messagingSenderId: '699693953835',
    projectId: 'harrier-central-mobile',
    databaseURL: 'https://harrier-central-mobile.firebaseio.com',
    storageBucket: 'harrier-central-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2YiFmDwcLCOdgm1BbuwVqJ0c_vmpI2cc',
    appId: '1:699693953835:ios:fde2c0279e05aa3a7a8b6e',
    messagingSenderId: '699693953835',
    projectId: 'harrier-central-mobile',
    databaseURL: 'https://harrier-central-mobile.firebaseio.com',
    storageBucket: 'harrier-central-mobile.firebasestorage.app',
    iosBundleId: 'com.example.hcportal',
  );
}
