// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwo7nAC02nMVQn36ULyyKIgmnKaxP5XKs',
    appId: '1:699693953835:android:a2108a4c6f6c2f877a8b6e',
    messagingSenderId: '699693953835',
    projectId: 'harrier-central-mobile',
    databaseURL: 'https://harrier-central-mobile.firebaseio.com',
    storageBucket: 'harrier-central-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2YiFmDwcLCOdgm1BbuwVqJ0c_vmpI2cc',
    appId: '1:699693953835:ios:683069737c7c7db4',
    messagingSenderId: '699693953835',
    projectId: 'harrier-central-mobile',
    databaseURL: 'https://harrier-central-mobile.firebaseio.com',
    storageBucket: 'harrier-central-mobile.firebasestorage.app',
    iosClientId: '699693953835-o537dp89b34r5nuvpo2p2t3r3sj3bs04.apps.googleusercontent.com',
    iosBundleId: 'com.harriercentral.app',
  );
}
