import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:uuid/uuid.dart';

part 'kennel_model.freezed.dart';
part 'kennel_model.g.dart';

class UuidConverter extends JsonConverter<UuidValue, String> {
  const UuidConverter();

  @override
  UuidValue fromJson(String json) => UuidValue.fromString(json);

  @override
  String toJson(UuidValue object) => object.toString();
}

@freezed
abstract class KennelModel with _$KennelModel {
  factory KennelModel({
    @UuidConverter() required UuidValue kennelPublicId,
    required String kennelName,
    required String kennelShortName,
    required String kennelUniqueShortName,
    required String kennelLogo,
    required String kennelDescription,
    required int excludeFromLeaderboard,
    required String cityName,
    required String regionName,
    required String countryName,
    required String continentName,
    required int kennelStatus,
    required int disseminateHashRunsDotOrg,
    required int disseminateAllowWebLinks,
    required int disseminationAudience,
    required int disseminateOnGlobalGoogleCalendar,
    required int canEditRunAttendence,
    required int kennelPinColor,
    required double defaultEventPriceForMembers,
    required double defaultEventPriceForNonMembers,
    required DateTime defaultRunStartTime,
    required int allowSelfPayment,
    required int allowNegativeCredit,
    @UuidConverter() required UuidValue cityId,
    @UuidConverter() required UuidValue provinceStateId,
    @UuidConverter() required UuidValue countryId,
    required int defaultRunTags1,
    required int defaultRunTags2,
    required int defaultRunTags3,
    required int membershipDurationInMonths,
    required int defaultDistancePreference,
    required int notificationMinutesBeforeRunForChatPushNotifications,
    required int notificationMinutesBeforeRunForCheckinReminder,
    required String extApiKey,
    double? latitude,
    double? longitude,
    double? defaultLatitude,
    double? defaultLongitude,
    //String? googleCalendarId,
    int? publishToGoogleCalendar,
    String? publishToGoogleCalendarAddresses,
    String? mismanagementTeam,
    String? kennelCoverPhoto,
    String? countryFlag,
    String? regionFlag,
    String? cityFlag,
    String? websiteBackgroundColor,
    String? websiteBackgroundImage,
    String? websiteTitleText,
    String? websiteMenuBackgroundColor,
    String? websiteMenuTextColor,
    String? websiteWelcomeText,
    String? websiteBodyTextColor,
    String? websiteTitleTextColor,
    String? websiteMismanagementDescription,
    String? websiteMismanagementJson,
    String? websiteExtraMenusJson,
    int? websiteControlFlags,
    String? websiteContactDetailsJson,
    String? websiteBannerImage,
    String? websiteUrlShortcode,
    String? websiteTitleFont,
    String? websiteBodyFont,
    String? kennelAdminEmailList,
    String? kennelWebsiteUrl,
    String? kennelEventsUrl,
    String? kennelHcEventsUrl,
    String? bankScheme,
    String? bankAccountNumber,
    String? bankBic,
    String? bankBeneficiary,
    String? kennelPaymentScheme,
    String? kennelPaymentUrl,
    DateTime? kennelPaymentUrlExpires,
    double? kennelPaymentMemberSurcharge,
    double? kennelPaymentNonMemberSurcharge,
    String? kennelPaymentScheme2,
    String? kennelPaymentUrl2,
    DateTime? kennelPaymentUrlExpires2,
    double? kennelPaymentMemberSurcharge2,
    double? kennelPaymentNonMemberSurcharge2,
    String? kennelPaymentScheme3,
    String? kennelPaymentUrl3,
    DateTime? kennelPaymentUrlExpires3,
    double? kennelPaymentMemberSurcharge3,
    double? kennelPaymentNonMemberSurcharge3,
    DateTime? runCountStartDate,
    int? distancePreference,
    String? kennelSearchTags,
  }) = _KennelModel;

  factory KennelModel.empty() => KennelModel(
        kennelPublicId: UuidValue.fromString(Uuid().v4()),
        kennelName: '',
        kennelShortName: '',
        kennelUniqueShortName: '',
        kennelLogo: '',
        kennelDescription: '',
        excludeFromLeaderboard: 0,
        cityName: '',
        regionName: '',
        countryName: '',
        continentName: '',
        kennelStatus: 0,
        disseminateHashRunsDotOrg: 0,
        disseminateAllowWebLinks: 0,
        disseminationAudience: 0,
        disseminateOnGlobalGoogleCalendar: 0,
        canEditRunAttendence: 0,
        kennelPinColor: 0,
        defaultEventPriceForMembers: 0,
        defaultEventPriceForNonMembers: 0,
        defaultRunStartTime: DateTime.fromMillisecondsSinceEpoch(0),
        allowSelfPayment: 0,
        allowNegativeCredit: 0,
        cityId: UuidValue.fromString(Uuid().v4()),
        provinceStateId: UuidValue.fromString(Uuid().v4()),
        countryId: UuidValue.fromString(Uuid().v4()),
        defaultRunTags1: 0,
        defaultRunTags2: 0,
        defaultRunTags3: 0,
        membershipDurationInMonths: 0,
        defaultDistancePreference: 0,
        notificationMinutesBeforeRunForChatPushNotifications: 0,
        notificationMinutesBeforeRunForCheckinReminder: 0,
        extApiKey: '',
        latitude: 0,
        longitude: 0,
        defaultLatitude: 0,
        defaultLongitude: 0,
      );

  factory KennelModel.fromJson(Map<String, dynamic> json) =>
      _$KennelModelFromJson(json);
}
