// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'kennel_website_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_KennelWebsiteModel _$KennelWebsiteModelFromJson(Map<String, dynamic> json) =>
    _KennelWebsiteModel(
      kennelId: const _UuidConverter().fromJson(json['kennelId'] as String),
      enabled: const _BoolConverter().fromJson(json['enabled']),
      customDomain: json['customDomain'] as String?,
      urlShortcode: json['urlShortcode'] as String?,
      themeMode: json['themeMode'] as String,
      primaryColor: json['primaryColor'] as String?,
      accentColor: json['accentColor'] as String?,
      scrollBlur: (json['scrollBlur'] as num).toInt(),
      bannerImage: json['bannerImage'] as String?,
      ogImageUrl: json['ogImageUrl'] as String?,
      backgroundImage: json['backgroundImage'] as String?,
      titleTextColor: json['titleTextColor'] as String?,
      bodyTextColor: json['bodyTextColor'] as String?,
      textMutedColor: json['textMutedColor'] as String?,
      cardBackgroundColor: json['cardBackgroundColor'] as String?,
      buttonPrimaryColor: json['buttonPrimaryColor'] as String?,
      buttonCancelColor: json['buttonCancelColor'] as String?,
      buttonSecondaryColor: json['buttonSecondaryColor'] as String?,
      runCardColor: json['runCardColor'] as String?,
      backgroundColor: json['backgroundColor'] as String?,
      menuBackgroundColor: json['menuBackgroundColor'] as String?,
      menuTextColor: json['menuTextColor'] as String?,
      titleFont: json['titleFont'] as String?,
      bodyFont: json['bodyFont'] as String?,
      titleText: json['titleText'] as String?,
      tagline: json['tagline'] as String?,
      welcomeText: json['welcomeText'] as String?,
      seoTitle: json['seoTitle'] as String?,
      seoDescription: json['seoDescription'] as String?,
      seoStructuredDataJson: json['seoStructuredDataJson'] as String?,
      mismanagementDescription: json['mismanagementDescription'] as String?,
      mismanagementJson: json['mismanagementJson'] as String?,
      extraMenusJson: json['extraMenusJson'] as String?,
      contactDetailsJson: json['contactDetailsJson'] as String?,
      controlFlags: (json['controlFlags'] as num?)?.toInt(),
    );

Map<String, dynamic> _$KennelWebsiteModelToJson(_KennelWebsiteModel instance) =>
    <String, dynamic>{
      'kennelId': const _UuidConverter().toJson(instance.kennelId),
      'enabled': const _BoolConverter().toJson(instance.enabled),
      'customDomain': instance.customDomain,
      'urlShortcode': instance.urlShortcode,
      'themeMode': instance.themeMode,
      'primaryColor': instance.primaryColor,
      'accentColor': instance.accentColor,
      'scrollBlur': instance.scrollBlur,
      'bannerImage': instance.bannerImage,
      'ogImageUrl': instance.ogImageUrl,
      'backgroundImage': instance.backgroundImage,
      'titleTextColor': instance.titleTextColor,
      'bodyTextColor': instance.bodyTextColor,
      'textMutedColor': instance.textMutedColor,
      'cardBackgroundColor': instance.cardBackgroundColor,
      'buttonPrimaryColor': instance.buttonPrimaryColor,
      'buttonCancelColor': instance.buttonCancelColor,
      'buttonSecondaryColor': instance.buttonSecondaryColor,
      'runCardColor': instance.runCardColor,
      'backgroundColor': instance.backgroundColor,
      'menuBackgroundColor': instance.menuBackgroundColor,
      'menuTextColor': instance.menuTextColor,
      'titleFont': instance.titleFont,
      'bodyFont': instance.bodyFont,
      'titleText': instance.titleText,
      'tagline': instance.tagline,
      'welcomeText': instance.welcomeText,
      'seoTitle': instance.seoTitle,
      'seoDescription': instance.seoDescription,
      'seoStructuredDataJson': instance.seoStructuredDataJson,
      'mismanagementDescription': instance.mismanagementDescription,
      'mismanagementJson': instance.mismanagementJson,
      'extraMenusJson': instance.extraMenusJson,
      'contactDetailsJson': instance.contactDetailsJson,
      'controlFlags': instance.controlFlags,
    };
